name: Daily Script Execution with Proxy

on:
  schedule:
    - cron: '30 17 * * *'  # Runs at 17:30 UTC every day
  workflow_dispatch:  # Enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y proxychains4

      - name: Configure proxychains
        run: |
          echo "strict_chain" | sudo tee /etc/proxychains4.conf
          echo "proxy_dns" | sudo tee -a /etc/proxychains4.conf
          echo "remote_dns_subnet 224" | sudo tee -a /etc/proxychains4.conf
          echo "tcp_read_time_out 15000" | sudo tee -a /etc/proxychains4.conf
          echo "tcp_connect_time_out 8000" | sudo tee -a /etc/proxychains4.conf
          echo "[ProxyList]" | sudo tee -a /etc/proxychains4.conf
          echo "socks5 198.23.239.134 6540 guivyfga 5tdsarxabmko" | sudo tee -a /etc/proxychains4.conf

      - name: Run Python Script through proxy
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          proxychains4 python main.py 2>&1 | tee output.log

      - name: Display Python script output
        if: always()
        run: |
          echo "Python Script Output:"
          cat output.log

      - name: Upload log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.log
