name: Daily Script Execution

on:
  schedule:
    - cron: '44 16 * * *'  # Runs at 16:44 UTC every day
  workflow_dispatch:  # Enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python main.py
          
      - name: Check for errors
        if: failure()
        run: |
          echo "The script failed. Here's the last few lines of the log:"
          tail -n 20 $GITHUB_WORKSPACE/github-actions.log
